export const nameColumsHangHoa = {
  Nhom: 'Nhóm',
  MaHang: 'Mã hàng',
  TenNhom: 'Tên Nhóm',
  TenHang: 'Tên Hàng',
  DVTKho: 'Đơn Vị Tính',
  TyLeQuyDoi: 'Tỷ Lệ Quy Đổi',
  DVTQuyDoi: 'Đơn Vị Tính (Quy Đổi)',
  DienGiaiDVTQuyDoi: 'DVT Quy Đổi',
  MaVach: 'Mã Vạch',
  DienGiaiHangHoa: 'Diển Giải Hàng Hóa',
  LapRap: 'Lắp Ráp',
  NA: 'Ngưng Dùng',
  TonKho: 'Tồn Kho',
  GhiChu: 'Ghi Chú',
  GiaBanLe: 'Giá Bán Lẻ',
  CoThue: 'Có Thuế',
  TyLeThue: 'Tỷ lệ Thuế',
  BangGiaSi: 'Bảng Giá Sỉ',
  BangGiaSi_Min: 'Bảng Giá Sỉ (Min)',
  BangGiaSi_Max: 'Bảng Giá Sỉ (Max)',
  NguoiTao: 'Người Tạo',
  NgayTao: 'Ngày Tạo',
  NguoiSuaCuoi: 'Người Sửa Cuối',
  NgaySuaCuoi: 'Ngày Sửa Cuối',
}

export const nameColumsPhieuBanHang = {
  SoChungTu: 'Số Chứng Từ',
  NgayCTu: 'Ngày Chứng Từ',
  DaoHan: 'Đáo Hạn',
  MaDoiTuong: 'Mã Đối Tượng',
  TenDoiTuong: 'Tên Đối Tượng',
  DiaChi: 'Địa Chỉ',
  MaSoThue: 'Mã Số Thuế',
  MaKho: 'Mã Kho',
  ThongTinKho: 'Thông Tin Kho',
  GhiChu: 'Ghi Chú',
  TongMatHang: 'Tổng Mặt Hàng',
  TongSoLuong: 'Tổng Số Lượng',
  TongTienHang: 'Tổng Tiền Hàng',
  TongTienThue: 'Tổng Tiền Thuế',
  TongThanhTien: 'Tổng Thành Tiền',
  TyLeCKTT: 'TLCK Thanh Toán',
  TongTienCKTT: 'Tổng CKT Toán',
  TongTongCong: 'Tổng Cộng',
  TTTienMat: 'Tiền Mặt',
  PhieuThu: 'Phiếu Thu',
  NguoiTao: 'Người Tạo',
  NgayTao: 'Ngày Tạo',
  NguoiSuaCuoi: 'Người Sửa Cuối',
  NgaySuaCuoi: 'Ngày Sửa Cuối',
}

export const nameColumsPhieuMuaHang = {
  STT: 'STT',
  MaHang: 'Mã hàng',
  TenHang: 'Tên hàng',
  DVT: 'DVT',
  SoLuong: 'Số lượng',
  DonGia: 'Đơn giá',
  TienHang: 'Tiền Hàng',
  TyLeThue: '% Thuế',
  TienThue: 'Tiền thuế',
  ThanhTien: 'Thành tiền',
}
export const nameColumsPhieuBanHangChiTiet = {
  STT: 'STT',
  MaHang: 'Mã hàng',
  TenHang: 'Tên hàng',
  DVT: 'DVT',
  SoLuong: 'Số lượng',
  DonGia: 'Đơn giá',
  TienHang: 'Tiền Hàng',
  TyLeThue: '% Thuế',
  TienThue: 'Tiền thuế',
  ThanhTien: 'Thành tiền',
  TyLeCKTT: '% CK Thanh Toán',
  TienCKTT: 'Tiền CK.Thanh Toán',
  TongCong: 'Tổng',
}
export const nameColumsNhapXuatTon = {
  STT: 'STT',
  MaHang: 'Mã hàng',
  TenHang: 'Tên hàng',
  DVT: 'ĐVT',
  MaNhomHang: 'Mã Nhóm Hàng',
  TenKho: 'Tên Kho',
  TenNhomHang: 'Tên Nhóm Hàng',
  MaKho: 'Mã Kho',
  SoLuongNhap: 'Số Lượng Nhập',
  SoLuongNhap_NCK: 'Nhập Chuyển Kho',
  SoLuongNhap_NDC: 'Nhập Điều Chỉnh',
  SoLuongNhap_NTR: 'Nhập Trả',
  SoLuongNhap_PMH: 'Nhập Mua Hàng',
  SoLuongTonCK: 'Tồn Cuối Kho',
  SoLuongTonDK: 'Tồn Đầu Kho',
  SoLuongXuat: 'Số Lượng Xuất',
  SoLuongXuat_HUY: 'Xuất Hủy',
  SoLuongXuat_PBL: 'Xuất Phiếu Bán Lẻ',
  SoLuongXuat_PBQ: 'Xuất Phiếu Bán Lẻ (Quầy)',
  SoLuongXuat_PBS: 'Xuất Phiếu Bán Sỉ',
  SoLuongXuat_XCK: 'Xuất Chuyển Kho',
  SoLuongXuat_XDC: 'Xuất Điều Chỉnh',
  SoLuongXuat_XSD: 'Xuất Sử Dụng',
  SoLuongXuat_XTR: 'Xuất Trả',
}
