export const nameColumsHangHoa = {
  Nhom: 'Nhóm',
  MaHang: 'Mã hàng',
  TenNhom: 'Tên nhóm',
  TenHang: 'Tên hàng',
  DVTKho: 'Đơn vị tính',
  TyLeQuyDoi: 'Tỷ lệ quy đổi',
  DVTQuyDoi: 'Đơn vị tính (quy đổi)',
  DienGiaiDVTQuyDoi: 'Đơn vị tính quy đổi',
  MaVach: 'Mã vạch',
  DienGiaiHangHoa: 'Diển giải hàng hóa',
  LapRap: 'Lắp ráp',
  NA: 'Ngưng dùng',
  TonKho: 'Tồn kho',
  GhiChu: 'Ghi chú',
  GiaBanLe: 'Giá bán lẻ',
  CoThue: 'Có thuế',
  TyLeThue: 'Tỷ lệ thuế',
  BangGiaSi: 'Bảng giá sỉ',
  BangGiaSi_Min: 'Bảng giá sỉ (Min)',
  BangGiaSi_Max: 'Bảng giá sỉ (Max)',
  NguoiTao: 'Người tạo',
  NgayTao: 'Ngày tạo',
  NguoiSuaCuoi: 'Người sửa cuối',
  NgaySuaCuoi: 'Ngày sửa cuối',
}
export const nameColumsDoiTuong = {
  Loai: 'Loại',
  TenLoai: 'Tên loại',
  Ma: 'Mã',
  Nhom: 'Nhóm',
  TenNhom: 'Tên nhóm',
  Ten: 'Tên',
  DiaChi: 'Địa chỉ',
  QuanHuyen: 'Quận huyện',
  TinhThanh: 'Tỉnh thành',
  NguoiLienHe: 'Người liên hệ',
  DienThoai: 'Điện thoại',
  Fax: 'Fax',
  Email: 'Email',
  MST: 'MST',
  ThongTinNhomGia: 'Nhóm giá',
  GhiChu: 'Ghi chú',
  NguoiTao: 'Người tạo',
  NgayTao: 'Ngày tạo',
  NguoiSuaCuoi: 'Người sửa cuối',
  NgaySuaCuoi: 'Ngày sửa cuối',
}
export const nameColumsNhomDoiTuong = {
  Ma: 'Mã',
  Ten: 'Tên',
  GhiChu: 'Ghi chú',
  NguoiTao: 'Người tạo',
  NgayTao: 'Ngày tạo',
  NguoiSuaCuoi: 'Người sửa cuối',
  NgaySuaCuoi: 'Ngày sửa cuối',
}
export const nameColumsHangMucThu = {
  Ma: 'Mã',
  Ten: 'Tên',
  GhiChu: 'Ghi chú',
  NguoiTao: 'Người tạo',
  NgayTao: 'Ngày tạo',
  NguoiSuaCuoi: 'Người sửa cuối',
  NgaySuaCuoi: 'Ngày sửa cuối',
}
export const nameColumsHangMucChi = {
  Ma: 'Mã',
  Ten: 'Tên',
  GhiChu: 'Ghi chú',
  NguoiTao: 'Người tạo',
  NgayTao: 'Ngày tạo',
  NguoiSuaCuoi: 'Người sửa cuối',
  NgaySuaCuoi: 'Ngày sửa cuối',
}
export const nameColumsNhomHang = {
  MaNhom: 'Mã',
  TenNhom: 'Tên',
  GhiChu: 'Ghi chú',
  NguoiTao: 'Người tạo',
  NgayTao: 'Ngày tạo',
  NguoiSuaCuoi: 'Người sửa cuối',
  NgaySuaCuoi: 'Ngày sửa cuối',
  NA: 'Ngưng dùng',
}
export const nameColumnsPhieuBanHang = {
  SoChungTu: 'Số chứng từ',
  NgayCTu: 'Ngày chứng từ',
  DaoHan: 'Đáo hạn',
  MaDoiTuong: 'Mã đối tượng',
  TenDoiTuong: 'Tên đối tượng',
  ThongTinHangHoa: 'Thông tin hàng',
  ThanhTien: 'Thành tiền',
  DiaChi: 'Địa chỉ',
  MaSoThue: 'Mã số thuế',
  MaKho: 'Mã kho',
  ThongTinKho: 'Thông tin kho',
  GhiChu: 'Ghi chú',
  TongMatHang: 'Tổng mặt hàng',
  TongSoLuong: 'Tổng số lượng',
  TongTienHang: 'Tổng tiền hàng',
  TongTienThue: 'Tổng tiền thuế',
  TongThanhTien: 'Tổng thành tiền',
  TyLeCKTT: 'TLCK thanh toán',
  TongTienCKTT: 'Tổng CKT toán',
  TongTongCong: 'Tổng cộng',
  TTTienMat: 'Tiền mặt',
  PhieuThu: 'Phiếu thu',
  NguoiTao: 'Người tạo',
  NgayTao: 'Ngày tạo',
  NguoiSuaCuoi: 'Người sửa cuối',
  NgaySuaCuoi: 'Ngày sửa cuối',
  DiaChiDoiTuong: 'Địa chỉ',
  MaHang: 'Mã hàng',
  TenHang: 'Tên hàng',
  DVT: 'Đơn vị tính',
  SoLuong: 'Số lượng',
  TienHang: 'Tiền hàng',
  TienThue: 'Tiền thuế',
  TienCKTT: 'Tiền Ch.Khấu',
  TongCong_TM: 'Tiền mặt',
  TongCong_CN: 'Công nợ',
  TongCong: 'Tổng cộng',
}
export const nameColumsPhieuMuaHang = {
  STT: 'STT',
  MaHang: 'Mã hàng',
  TenHang: 'Tên hàng',
  DVT: 'ĐVT',
  SoLuong: 'Số lượng',
  DonGia: 'Đơn giá',
  GiaBan: 'Giá bán',
  CoThue: 'Đã có thuế',
  TienHang: 'Tiền hàng',
  TyLeThue: '% Thuế',
  TienThue: 'Tiền thuế',
  ThanhTien: 'Thành tiền',
}
export const nameColumsGBS = {
  STT: 'STT',
  MaHang: 'Mã hàng',
  TenHang: 'Tên hàng',
  DVT: 'ĐVT',
  DonGia: 'Đơn giá',
  CoThue: 'Đã có thuế',
  TyLeThue: '% Thuế',
}
export const nameColumsPhieuBanHangChiTiet = {
  STT: 'STT',
  MaHang: 'Mã hàng',
  TenHang: 'Tên hàng',
  DVT: 'ĐVT',
  SoLuong: 'Số lượng',
  DonGia: 'Đơn giá',
  TienHang: 'Tiền hàng',
  TyLeThue: '% Thuế',
  TienThue: 'Tiền thuế',
  ThanhTien: 'Thành tiền',
  TyLeCKTT: '% CK thanh toán',
  TienCKTT: 'Tiền CK.thanh toán',
  TongCong: 'Tổng',
}
export const nameColumsNhapXuatTon_TheoKho = {
  STT: 'STT',
  MaHang: 'Mã hàng',
  TenHang: 'Tên hàng',
  DVT: 'Đơn vị tính',
  MaNhomHang: 'Mã nhóm hàng',
  TenKho: 'Tên kho',
  TenNhomHang: 'Tên nhóm hàng',
  MaKho: 'Mã kho',
  SoLuongNhap: 'Tổng nhập',
  SoLuongNhap_NCK: 'Chuyển kho',
  SoLuongNhap_NDC: 'Điều chỉnh',
  SoLuongNhap_NTR: 'Trả hàng',
  SoLuongNhap_PMH: 'Mua hàng',
  SoLuongTonCK: 'Tồn cuối',
  SoLuongTonDK: 'Tồn đầu',
  SoLuongXuat: 'Tổng xuất',
  SoLuongXuat_HUY: 'Hủy',
  SoLuongXuat_PBL: 'Bán lẻ',
  SoLuongXuat_PBQ: 'Bán lẻ (Quầy)',
  SoLuongXuat_PBS: 'Bán sỉ',
  SoLuongXuat_XCK: 'Chuyển kho',
  SoLuongXuat_XDC: 'Điều chỉnh',
  SoLuongXuat_XSD: 'Sử dụng',
  SoLuongXuat_XTR: 'Trả hàng',
}
export const nameColumsNhapXuatTon_TongKho = {
  STT: 'STT',
  TenNhomHang: 'Nhóm',
  MaHang: 'Mã hàng',
  TenHang: 'Tên hàng',
  DVT: 'Đơn vị tính',
  SoLuongTonDK: 'S.Lượng Tồn đầu',
  TriGiaTonDK: 'T.Giá Tồn đầu',
  SoLuongNhap_PMH: 'S.Lượng Mua hàng',
  TriGiaNhap_PMH: 'T.Giá Mua hàng',
  SoLuongNhap_NTR: 'S.Lượng Trả hàng',
  TriGiaNhap_NTR: 'T.Giá Trả hàng',
  SoLuongNhap: 'S.Lượng Nhập tổng',
  TriGiaNhap: 'T.Giá Nhập tổng',
  SoLuongNhap_NDC: 'S.Lượng Điều chỉnh',
  TriGiaNhap_NDC: 'T.Giá Điều chỉnh',
  SoLuongTonCK: 'S.Lượng Tồn cuối',
  TriGiaTonCK: 'T.Giá Tồn cuối',
  SoLuongXuat: 'S.Lượng Xuất',
  TriGiaXuat: 'T.Giá Xuất',
  SoLuongXuat_HUY: 'S.Lượng Hủy',
  TriGiaXuat_HUY: 'T.Giá Hủy',
  SoLuongXuat_PBL: 'S.Lượng Bán lẻ',
  TriGiaXuat_PBL: 'T.Giá Bán lẻ',
  SoLuongXuat_PBQ: 'S.Lượng Bán lẻ (Quầy)',
  TriGiaXuat_PBQ: 'T.Giá Bán lẻ (Quầy)',
  SoLuongXuat_PBS: 'S.Lượng Bán sỉ',
  TriGiaXuat_PBS: 'T.Giá Bán sỉ',
  SoLuongXuat_XDC: 'S.Lượng Điều chỉnh',
  TriGiaXuat_XDC: 'T.Giá Điều chỉnh',
  SoLuongXuat_XSD: 'S.Lượng Sử dụng',
  TriGiaXuat_XSD: 'T.Giá Sử dụng',
  SoLuongXuat_XTR: 'S.Lượng Trả',
  TriGiaXuat_XTR: 'T.Giá Trả',
}

export const nameColumsDSBHKHO = {
  STT: 'STT',
  NhomHang: 'Nhóm',
  MaHang: 'Mã hàng',
  TenHang: 'Tên hàng',
  DVT: 'Đơn vị tính',
  Le_TienHang: 'Lẻ - Tiền hàng',
  Si_TienHang: 'Sỉ - Tiền hàng',
  TienHang: 'Tiền hàng',
  Le_TienThue: 'Lẻ - Tiền thuế',
  Si_TienThue: 'Sỉ - Tiền thuế',
  TienThue: 'Tiền thuế',
  Le_ThanhTien: 'Lẻ - Thành tiền',
  Si_ThanhTien: 'Sỉ - Thành tiền',
  ThanhTien: 'Thành tiền',
  Le_ChietKhau: 'Lẻ - Chiết khấu',
  Si_ChietKhau: 'Sỉ - Chiết khấu',
  ChietKhau: 'Chiết khấu',
  Le_TongCong: 'Lẻ - Tổng Cộng',
  Si_TongCong: 'Sỉ - Tổng cộng',
  TongCong: 'Tổng cộng',
}
export const nameColumsDSBHHH = {
  MaHang: 'Mã hàng',
  TenHang: 'Tên hàng',
  DVT: 'ĐVT',
  ThongTinHangHoa: 'Thông tin hàng hóa',
  SoLuong: 'Số lượng',
  TienHang: 'Tiền hàng',
  TienThue: 'Tiền thuế',
  ThanhTien: 'Thành tiền',
  TienCKTT: 'Chiết khấu',
  TongCong: 'Tổng cộng',
  TongCong_TM: 'Tiền mặt',
  TongCong_CN: 'Công nợ',
  // Khách hàng
  MaDoiTuong: 'Mã khách hàng',
  TenDoiTuong: 'Tên khách hàng',
  DiaChiDoiTuong: 'Địa chỉ',
}
export const nameColumsDSBHQUAY = {
  STT: 'STT',
  NhomHang: 'Nhóm',
  MaHang: 'Mã hàng',
  TenHang: 'Tên hàng',
  DVT: 'Đơn vị tính',
  TienHang: 'Tiền hàng',
  TienThue: 'Tiền thuế',
  ThanhTien: 'Thành tiền',
  ChietKhau: 'Chiết khấu',
  TongCong: 'Tổng cộng',
}
export const nameColumsSoQuy = {
  ID: 'ID',
  Loai: 'Loại',
  SapXep: 'Sắp xếp',
  NgayCTu: 'Ngày chứng từ',
  SoChungTu: 'Số chứng từ',
  GhiChu: 'Ghi chú',
  THUCONGNO: 'Thu công nợ',
  THUTRAHANG: 'Thu trả hàng',
  THUKHAC: 'Thu khác',
  CHICONGNO: 'Chi công nợ',
  CHITRAHANG: 'Chi trả hàng',
  CHIKHAC: 'Chi khác',
  DauKy: 'Đầu kỳ',
  CuoiKy: 'Cuối kỳ',
  ConLai: 'Còn lại',
}
export const nameColumsPhieuNTR = {
  STT: 'STT',
  SoChungTu: 'Số chứng từ',
  NgayCTu: 'Ngày chứng từ',
  DaoHan: 'Đáo hạn',
  MaDoiTuong: 'Mã đối tượng',
  TenDoiTuong: 'Tên đối tượng',
  DiaChi: 'Địa chỉ',
  MaSoThue: 'Mã số thuế',
  MaKho: 'Mã kho',
  ThongTinKho: 'Thông tin kho',
  GhiChu: 'Ghi chú',
  TongMatHang: 'Tổng mặt hàng',
  TongSoLuong: 'Tổng số lượng',
  TongTienHang: 'Tổng tiền hàng',
  TongTienThue: 'Tổng tiền thuế',
  TongThanhTien: 'Tổng thành tiền',
  TyLeCKTT: 'TLCK thanh toán',
  TongTienCKTT: 'Tổng CKT toán',
  TongTongCong: 'Tổng cộng',
  TTTienMat: 'Tiền mặt',
  PhieuThu: 'Phiếu Thu',
  NguoiTao: 'Người tạo',
  NgayTao: 'Ngày tạo',
  NguoiSuaCuoi: 'Người sửa cuối',
  NgaySuaCuoi: 'Ngày sửa cuối',
  PhieuChi: 'Phiếu chi',
}
export const nameColumsPhieuNhapDieuChinh = {
  STT: 'STT',
  MaHang: 'Mã hàng',
  TenHang: 'Tên hàng',
  DVT: 'ĐVT',
  SoLuong: 'Số lượng',
  SoChungTu: 'Số chứng từ',
  NgayCTu: 'Ngày chứng từ',
  SoThamChieu: 'Số tham chiếu',
  MaKho: 'Mã kho',
  ThongTinKho: 'Thông tin kho',
  MaKho_Nhan: 'Mã kho nhận',
  ThongTinKhoNhan: 'Thông tin kho nhận',
  GhiChu: 'Ghi chú',
  SoMatHang: 'Số mặt hàng',
  TongSoLuong: 'Tổng số lượng',
  NguoiTao: 'Người tạo',
  NgayTao: 'Ngày tạo',
  NguoiSuaCuoi: 'Người sửa cuối',
  NgaySuaCuoi: 'Ngày sửa cuối',
  TongTriGiaKho: 'Tổng trị giá',
}
export const nameColumsPhieuLapRap = {
  STT: 'STT',
  MaHang: 'Mã hàng',
  TenHang: 'Tên hàng',
  DVT: 'ĐVT',
  SoLuong: 'Số lượng',
  SoChungTu: 'Số chứng từ',
  NgayCTu: 'Ngày chứng từ',
  MaKho: 'Mã kho',
  ThongTinKho: 'Thông tin kho',
  GhiChu: 'Ghi chú',
  SoMatHang: 'Số mặt hàng',
  TongSoLuong: 'Tổng số lượng',
  NguoiTao: 'Người tạo',
  NgayTao: 'Ngày tạo',
  NguoiSuaCuoi: 'Người sửa cuối',
  NgaySuaCuoi: 'Ngày sửa cuối',
}
export const nameColumsPhieuXuatDieuChinh = {
  STT: 'STT',
  MaHang: 'Mã hàng',
  TenHang: 'Tên hàng',
  DVT: 'ĐVT',
  SoLuong: 'Số lượng',
  SoChungTu: 'Số chứng từ',
  NgayCTu: 'Ngày chứng từ',
  SoThamChieu: 'Số tham chiếu',
  MaKho: 'Mã kho',
  ThongTinKho: 'Thông tin kho',
  MaKho_Nhan: 'Mã kho nhận',
  ThongTinKhoNhan: 'Thông tin kho nhận',
  GhiChu: 'Ghi chú',
  SoMatHang: 'Số mặt hàng',
  TongSoLuong: 'Tổng số lượng',
  NguoiTao: 'Người tạo',
  NgayTao: 'Ngày tạo',
  NguoiSuaCuoi: 'Người sửa cuối',
  NgaySuaCuoi: 'Ngày sửa cuối',
  TongTriGiaKho: 'Tổng trị giá',
}
export const nameColumsPhieuXuatChuyenKho = {
  STT: 'STT',
  MaHang: 'Mã hàng',
  TenHang: 'Tên hàng',
  DVT: 'ĐVT',
  SoLuong: 'Số lượng',
  SoChungTu: 'Số chứng từ',
  NgayCTu: 'Ngày chứng từ',
  SoThamChieu: 'Số tham chiếu',
  MaKho: 'Mã kho',
  ThongTinKho: 'Kho',
  MaKho_Nhan: 'Mã kho nhận',
  ThongTinKhoNhan: 'Kho nhận',
  GhiChu: 'Ghi chú',
  SoMatHang: 'Số mặt hàng',
  TongSoLuong: 'Tổng số lượng',
  NguoiTao: 'Người tạo',
  NgayTao: 'Ngày tạo',
  NguoiSuaCuoi: 'Người sửa cuối',
  NgaySuaCuoi: 'Ngày sửa cuối',
  XacNhan: 'Xác nhận',
}
export const nameColumsPhieuNhapChuyenKho = {
  STT: 'STT',
  MaHang: 'Mã hàng',
  TenHang: 'Tên hàng',
  DVT: 'ĐVT',
  SoLuong: 'Số lượng',
  SoChungTu: 'Số chứng từ',
  NgayCTu: 'Ngày chứng từ',
  SoThamChieu: 'Chứng từ gốc',
  MaKho: 'Mã kho',
  ThongTinKho: 'Thông tin kho',
  MaKho_Nhan: 'Mã kho nhận',
  ThongTinKhoNhan: 'Thông tin kho nhận',
  GhiChu: 'Ghi chú',
  SoMatHang: 'Số mặt hàng',
  TongSoLuong: 'Tổng số lượng',
  NguoiTao: 'Người tạo',
  NgayTao: 'Ngày tạo',
  NguoiSuaCuoi: 'Người sửa cuối',
  NgaySuaCuoi: 'Ngày sửa cuối',
}
export const nameColumsPhieuXuatSuDung = {
  STT: 'STT',
  MaHang: 'Mã hàng',
  TenHang: 'Tên hàng',
  DVT: 'ĐVT',
  SoLuong: 'Số lượng',
  SoChungTu: 'Số chứng từ',
  NgayCTu: 'Ngày chứng từ',
  SoThamChieu: 'Số tham chiếu',
  MaKho: 'Mã kho',
  ThongTinKho: 'Thông tin kho',
  MaKho_Nhan: 'Mã kho nhận',
  ThongTinKhoNhan: 'Thông tin kho nhận',
  GhiChu: 'Ghi chú',
  SoMatHang: 'Số mặt hàng',
  TongSoLuong: 'Tổng số lượng',
  NguoiTao: 'Người tạo',
  NgayTao: 'Ngày tạo',
  NguoiSuaCuoi: 'Người sửa cuối',
  NgaySuaCuoi: 'Ngày sửa cuối',
  TongTriGiaKho: 'Tổng trị giá',
}
export const nameColumsPhieuXuatHuy = {
  STT: 'STT',
  MaHang: 'Mã hàng',
  TenHang: 'Tên hàng',
  DVT: 'ĐVT',
  SoLuong: 'Số lượng',
  SoChungTu: 'Số chứng từ',
  NgayCTu: 'Ngày chứng từ',
  SoThamChieu: 'Số tham chiếu',
  MaKho: 'Mã kho',
  ThongTinKho: 'Thông tin kho',
  MaKho_Nhan: 'Mã kho nhận',
  ThongTinKhoNhan: 'Thông tin kho nhận',
  GhiChu: 'Ghi chú',
  SoMatHang: 'Số mặt hàng',
  TongSoLuong: 'Tổng số lượng',
  NguoiTao: 'Người tạo',
  NgayTao: 'Ngày tạo',
  NguoiSuaCuoi: 'Người sửa cuối',
  NgaySuaCuoi: 'Ngày sửa cuối',
  TongTriGiaKho: 'Tổng trị giá',
}
export const nameColumsKhoHang = {
  MaKho: 'Mã',
  TenKho: 'Tên',
  TenDayDu: 'Tên cửa hàng',
  DienThoai: 'Điện thoại',
  DiaChi: 'Địa chỉ',
  NguoiLienHe: 'Người liên hệ',
  GhiChu: 'Ghi chú',
  NguoiTao: 'Người tạo',
  NgayTao: 'Ngày tạo',
  NguoiSuaCuoi: 'Người sửa cuối',
  NgaySuaCuoi: 'Ngày sửa cuối',
}
export const nameColumsQuanLy = {
  ID: 'ID',
  MaQuanLy: 'Mã quản lý',
  MaNguoiDung: 'Mã người dùng',
  TenNguoiDung: 'Tên người dùng',
  TuNgay: 'Hiệu lực từ',
  DenNgay: 'Ngày hết hạn',
  KhongKetThuc: 'Không kết thúc',
  NA: 'Ngưng dùng',
  GhiChu: 'Ghi chú',
  NguoiTao: 'Người tạo',
  NgayTao: 'Ngày tạo',
  NguoiSuaCuoi: 'Người sửa cuối',
  NgaySuaCuoi: 'Ngày sửa cuối',
}
export const nameColumsQuayTinhTien = {
  Quay: 'Quầy',
  TenMayTinh: 'Tên máy tính',
  SQLServer: 'Trạm SQL',
  SQLDatabase: 'Dữ liệu',
  SQLUser: 'User',
  SQLPassword: 'Password',
  MaKho: 'Mã kho',
  NhomGia: 'Nhóm giá',
  CungHeThong: 'Cùng hệ thống',
  CungServer: 'Cùng Server',
  Loai: 'Mã loại',
  DienGiaiLoai: 'Loại',
  NA: 'Ngưng dùng',
  CoLinkServer: 'Link-Server',
  GhiChu: 'Ghi chú',
  NguoiTao: 'Người tạo',
  NgayTao: 'Ngày tạo',
  NguoiSuaCuoi: 'Người sửa cuối',
  NgaySuaCuoi: 'Ngày sửa cuối',
  NguoiCNHTCuoi: 'Người C.nhật H.thống',
  NgayCNHTCuoi: 'Ngày C.nhật H.thống',
  NguoiCNTLCuoi: 'Người C.nhật T.lập',
  NgayCNTLCuoi: 'Ngày C.nhật T.lập',
}
export const nameColumsPhanCaDS = {
  SoQuay: 'Quầy',
  MaNguoiDung: 'Người dùng',
  TenNguoiDung: 'Tên người dùng',
  HieuLucTu: 'Kể từ ngày',
  MaCa: 'Ca',
  GhiChu: 'Ghi chú',
  NguoiTao: 'Người tạo',
  NgayTao: 'Ngày tạo',
  NguoiSuaCuoi: 'Người sửa cuối',
  NgaySuaCuoi: 'Ngày sửa cuối',
}
export const nameColumsCongNoDauRa = {
  MaDoiTuong: 'Mã khách hàng',
  TenDoiTuong: 'Tên khách hàng',
  DiaChiDoiTuong: 'Địa chỉ',
  SoDuDK: 'Số dư đầu',
  PhatSinhNo_PBS: 'Bán hàng',
  PhatSinhNo_DC: 'Điều chỉnh phát sinh',
  PhatSinhNo_Chi_NTR: 'Chi trả hàng',
  PhatSinhNo: 'Tổng phát sinh nợ',
  ThanhToan_Thu_PBS: 'Thu công nợ',
  ThanhToan_DC: 'Điều chỉnh công nợ',
  ThanhToan_NTR: 'Trả hàng',
  ThanhToan: 'Tổng thanh toán',
  SoDuCK: 'Số dư cuối',
}
export const nameColumsCongNoDauVao = {
  MaDoiTuong: 'Mã khách hàng',
  TenDoiTuong: 'Tên khách hàng',
  DiaChiDoiTuong: 'Địa chỉ',
  SoDuDK: 'Số dư đầu',
  PhatSinhNo_PMH: 'PS Mua hàng',
  PhatSinhNo_PBS: 'PS Bán hàng',
  PhatSinhNo_DC: 'PS Điều chỉnh',
  PhatSinhNo_Thu_XTR: 'PS Thu trả',
  PhatSinhNo_Chi_NTR: 'PS Chi trả',
  PhatSinhNo: 'Tổng phát sinh',
  ThanhToan_Chi_PMH: 'TT Chi hàng',
  ThanhToan_Thu_PBS: 'TT Thu công nợ',
  ThanhToan_DC: 'TT Điều chỉnh',
  ThanhToan_XTR: 'TT Trả hàng',
  ThanhToan_NTR: 'TT Trả hàng',
  ThanhToan: 'Tổng thanh toán',
  SoDuCK: 'Số dư cuối',
}
export const nameColumsDoanhSoBanHangHH = {
  MaHang: 'Mã hàng',
  TenHang: 'Tên hàng',
  DVT: 'Đơn vị tính',
  ThongTinHangHoa: 'Thông tin hàng',
  SoLuong: 'Số lượng',
  TienHang: 'Tiền hàng',
  TienThue: 'Tiền thuế',
  ThanhTien: 'Thành tiền',
  TienCKTT: 'Tiền chiết khấu',
  TongCong_TM: 'Tiền mặt',
  TongCong_CN: 'Công nợ',
  TongCong: 'Tổng cộng',
}
export const nameColumsDoanhSoBanHangKH = {
  MaDoiTuong: 'Mã hàng',
  TenDoiTuong: 'Tên hàng',
  DiaChiDoiTuong: 'Địa chỉ',
  TongCong: 'Tổng cộng',
  TongCong_TM: 'Tiền mặt',
  TongCong_CN: 'Công nợ',
}
export const nameColumsImport = {
  STT: 'STT',
  MaHang: 'Mã hàng',
  TenHang: 'Tên hàng',
  DVT: 'ĐVT',
  DonGia: 'Giá bán',
  CoThue: 'Đã có thuế',
  TyLeThue: '% Thuế',
}
export const nameColumsBinhQuanXuatKho = {
  Thang: 'Tháng',
  ThangFormat: 'Tháng',
  NhomHang: 'Nhóm hàng',
  MaHang: 'Mã hàng',
  TenHang: 'Tên hàng',
  DVT: 'ĐVT',
  DonGia: 'Đơn giá',
  NgayTao: 'Ngày tạo',
  NguoiTao: 'Người tạo',
  DaXuLy: 'Xử lý',
  NguoiThucHien: 'Thực hiện',
  ThoiGianThucHien: 'Lúc',
}
